version: '3'

services:
    brevets:
        build: brevets/.
        command: python -u flask_brevets.py
        ports: 
            - "5001:5000"
        depends_on:
            - brevetdb
        environment:
            MONGODB_HOSTNAME: brevetdb
        volumes:
          - type: bind
            source: brevets/
            target: /app
    brevetdb:
        image: mongo:5.0.5